ALTER TABLE USUARIOS ADD COLUMN peso_atual INTEGER;
ALTER TABLE USUARIOS ADD COLUMN altura_atual INTEGER;
ALTER TABLE USUARIOS ADD COLUMN braco_atual INTEGER;
ALTER TABLE USUARIOS ADD COLUMN quadril_atual INTEGER;
ALTER TABLE USUARIOS ADD COLUMN cintura_atual INTEGER;
ALTER TABLE USUARIOS ADD COLUMN coxa_atual INTEGER;
ALTER TABLE USUARIOS ADD COLUMN umbigo_atual INTEGER;